### ISSUE TITLE
Scroll up not working without dunstify

### ISSUE THREAD

**Issue by thomas-forbes** [jbirnick/polybar-timer#3]
When you don't have dunstify installed the scroll up functionality described in the readme doesn't work. This is because when you `./polybar-timer.sh increase 60` you get `./polybar-timer.sh: line 20: dunstify: command not found` and an error which means it will create a new timer overwriting the increase.

**Comment by jbirnick** [comment]
Yes. That is also more or less mentioned in the README:

> Inside the script dunstify is called to view the mentioned notification for the expiry time. But this is not necessary. (Just beautiful.) If you do not use Dunst than still everything (but the preview of the expiry time) will work fine without dependencies.

In that case you would have to edit the script yourself. I want to keep it as simple as possible, and I'm not going to introduce a config or anything.

For example you can modify the `printExpiryTime` and `deleteExpiryTime` functions so that they do nothing:
```bash
printExpiryTime () {}
deleteExpiryTime () {}
```

**Comment by CNote1** [comment]
I've got syntax error after editing these lines.

**Comment by jbirnick** [comment]
Thanks, I've edited it. Now it should work.

**Comment by raffaem** [comment]
Why not use `notify-send`?

**Comment by jbirnick** [comment]
Look at this screen recording:

![expiryTimePreview](https://github.com/jbirnick/polybar-timer/assets/6528009/0ee0693e-c6e2-4163-aba6-5b91460cc2fe)

The notification is _updated_ when you scroll. This is not possibly with `notify-send`. With `notify-send` you could only spam new notifications, and then you suddenly have 50 notifications on your desktop.

**Comment by jbirnick** [comment]
Now it only uses `notify-send`.
