### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by gitduk** [jbirnick/polybar-timer#6]
I don't have this files (/tmp/polybar-timer/*), can you post it ?

```
killTimer () { rm -rf /tmp/polybar-timer ; }
timerSet () { [ -e /tmp/polybar-timer/ ] ; }
timerPaused () { [ -f /tmp/polybar-timer/paused ] ; }

timerExpiry () { cat /tmp/polybar-timer/expiry ; }
timerLabelRunning () { cat /tmp/polybar-timer/label_running ; }
timerLabelPaused () { cat /tmp/polybar-timer/label_paused ; }
timerAction () { cat /tmp/polybar-timer/action ; }
```

**Comment by jbirnick** [comment]
Those are temporary files. (that's why they lie in /tmp/) They get created by the script, for example in those lines:
```bash
echo "$(( $(now) + 60*${2} ))" > /tmp/polybar-timer/expiry
echo "${3}" > /tmp/polybar-timer/label_running
echo "${4}" > /tmp/polybar-timer/label_paused
echo "${5}" > /tmp/polybar-timer/action
```

**Comment by gitduk** [comment]
@jbirnick 
i know 
I can't find your clock symbols on the internet, can you post them.

**Comment by jbirnick** [comment]
I use [Nerd Fonts](https://www.nerdfonts.com/), which brings a lot of icons with. On the [Cheat Sheet](https://www.nerdfonts.com/cheat-sheet) you can search for "time" or "clock" to find some. I use `fa1a` (nf-mdi-timer) and `fa1d` (nf-mdi-timer_off).
